# Generated by Django 2.1.2 on 2018-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='菜单名')),
                ('code', models.CharField(max_length=255, verbose_name='菜单编码')),
                ('content_type_id', models.IntegerField(default=0, verbose_name='模块ID')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否为根目录')),
                ('father_code', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='父节点')),
                ('has_children', models.BooleanField(default=False, verbose_name='是否有子节点')),
                ('href', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='菜单路径')),
                ('icon', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='菜单图标')),
                ('component', models.CharField(default='baseType', max_length=255, verbose_name='组件类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
            },
        ),
    ]
